### ISSUE TITLE
[*] Error: 'data'

### ISSUE THREAD

**Issue by tuanteku9x** [Fairmont77/OKX_Racer_bot#1]
[*] Error: 'data'
Pro

**Comment by Fairmont77** [comment]
I'm working on it, just wait

**Comment by tuanteku9x** [comment]
> I'm working on it, just wait

haha, can you set: btc price alway up?

**Comment by Fairmont77** [comment]
> > I'm working on it, just wait
> 
> haha, can you set: btc price alway up?

ok)

**Comment by Fairmont77** [comment]
> > I'm working on it, just wait
> 
> haha, can you set: btc price alway up?

git pull
Try updated code, don't pay much attention to the errors)

**Comment by tuanteku9x** [comment]
> > > I'm working on it, just wait
> > 
> > 
> > haha, can you set: btc price alway up?
> 
> git pull Try updated code, don't pay much attention to the errors)

thank you for your tool

**Comment by tuanteku9x** [comment]
Pro, I see it show:
Wait 90 Seconds to continue ...
But 5 second before?

**Comment by Fairmont77** [comment]
> Pro, I see it show: Wait 90 Seconds to continue ... But 5 second before?

If you want 5, you can write self.countdown(5) instead of self.countdown(assess_data['secondToRefresh'] + 5)

**Comment by Fairmont77** [comment]
> Pro, I see it show: Wait 90 Seconds to continue ... But 5 second before?

I try my make new version with proxy, fingerprint, multi accs.... I need few days(

**Comment by tuanteku9x** [comment]
> self.countdown

Hmm i see 5... but why more than 90?
Nothing change your code OGM.
__pycache__ ??

**Comment by Fairmont77** [comment]
> > self.countdown
> 
> Hmm i see 5... but why more than 90? Nothing change your code OGM. **pycache** ??

If it shows that there are no more chances, but a boost is available to reload the fuel tank (id = 1), and its stage has not reached the maximum, then the boost is used and the process is repeated. If there are still chances (numChance > 0), the program pauses for 5 seconds and continues. If it needs to refresh, it waits the specified number of seconds plus 5, otherwise it exits the loop.
It all depends on the api, how long it takes to refresh, I need to think about it
